baseURL = "https://itigentech.github.io/itigen/"
languageCode = "ja"
title = "ITIGEN"
publishDir = "docs"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "https://www.googletagmanager.com/gtag/js?id=UA-122087163-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = "https://twitter.com/itigentech"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/hero_image.jpg"
  recent_posts_number = 2
